# This is a basic workflow to help you get started with Actions

name: test-workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      solution-names:
        description: "Solution Name(s)"
        type: string
        required: true
        default: 'contoso_university_core, ContosoUniversityExtended'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set Solution Names Matrix
        run: | 
          if ('${{inputs.solution-names}}' -match ','){
            $solutionNames = @()
            '${{inputs.solution-names}}' -split ',' | foreach { 
              $solutionNames += $_.Trim()
              write-host $_.Trim()
            }
          }
          else {
            $solutionNames = '${{inputs.solution-names}}'
          }
          write-host $solutionNames
          echo "solution-names=$solutionNames" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append;
        shell: pwsh 
      - name: Output Solution Names
        run: echo ${{ env.solution-names }}
      - name: Checkout new Branch 
        uses: actions/checkout@v4
        with:
           ref: main
           path: PowerPlatformALM
      - name: Checkout Template Branch 
        uses: actions/checkout@v4
        with:
          repository: Contoso-W-Enterprise/PowerPlatformALM
          ref: V1
          path: ALMTemplate
          github-server-url: 'https://github.com'
          lfs: true
          persist-credentials: true
      - name: Debug list of files
        run: |
          Get-ChildItem -path '.' -Recurse | foreach { write-host $_.FullName }
        shell: pwsh
  deploy:
    strategy:
      matrix:
        solutions-Names: ${{ env.solution-names }}
    runs-on: ubuntu-latest
    steps:
      - name: output matrix
        run: echo ${{ matrix.solutions-names}}
      